### PR TITLE
Add the possibility to attach an existing member to the client.

### PR DESCRIPTION
**Pull request by erozqba**
*Fixes issue #223 .*

### Changes proposed in this pull request:

* Update the tests because in a previous commit I had used assertTrue instead of assterEqual
* Add a route and a view for making ajax request in order to
find the existing members.
* Update the templates to add the new input to search existing
members and the JavaScript code needed.
* Update the view ClientWizard to add the existing member to the
client when needed, also split the long save method into several
logic methods that are reused in the save method.

 * Important change : Right now I have decided that if the
client information and the payment information is the same
(First Name and Last Name) only one member is created in the
DataBase, because if not we end with lots of members that basically
have the same information. Is the same with the payment information
and the referent information, maybe the person referencing the
client is the same that will pay for it, and right now we create
two differents members in the DataBase. I'm not sure how this should
be handled and I will be happy to change this into the right way.

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### Deployment notes and migration

- [ ] Migration needed

### CODE REVIEW

**Comment by maximest-pierre** [comment]
Everything looks good except the coverage has taken a hit. Can you look at improving the coverage.

Thank you.

**Comment by erozqba** [comment]
@maximest-pierre I will look into it when I have the time.

**Comment by erozqba** [comment]
Hi @maximest-pierre, I have looked into the coverage and increased it for the current work, so it should be ready to be merged.

I find out that the coverage can be increased in other areas, I will try to look at it when I have more free time.

**Comment by maximest-pierre** [comment]
It looks good to me. Thanks for the PR.

**Pull request merged**
