### PR TITLE
WIP Add order form

### LINKED ISSUE #239: Add an order creation form
Some work has already be done on the **factory-boy/orders** branch. Please base your work on top of this branch.

### Expected Behaviour

- [ ] Provide a form to create an order
- [ ] Must include a sub-form to add all sort of order items tot the order
- [ ] This sub form must be reusable to be displayed from the order view (could be displayed in a modal window, SemanticUi supports it)
- [ ] A factory must be implemented, to easily create batch of orders, for development and testing purposes
- [x] A command can also be implemented: ` python manage.py createorders` (see **createclients**, which is already implemented)
- [ ] The form and the view must be tested

### Actual Behaviour

* Only the Django backend allow order creation

### PR DESCRIPTION
**Pull request by erozqba**
*Fixes #239  .*

### Changes proposed in this pull request:

* Add the form to create new orders
* Add django-extra-views dependency
* Add django-dynamic-formset dependency
* Use CBV instead FBV

* TODO: Add tests.

### Status

- [X] WIP (Work-In-Progress)

### Deployment notes and migration

- [ ] Migration needed

This is a work in progress, I'm trying to understand the Django "Formsets", "Modelsformset" and "Inlineformset" to make this work, any comments or help will be appreciated.  Do you think that use "Formsets", "Modelsformset" and "Inlineformset" with the package "django-extra-views" is a good option? Or do you have other think in mind?

@savoirfairelinux/mll

### CODE REVIEW

**Comment by erozqba** [comment]
Hi @manumilou, @lamontfr, @maximest-pierre 
Any ideas of a better way of doing this?
I will add tests if you find this will do the job...

**Comment by lamontfr** [comment]
Hi Ernesto,

I will have a look today and let you know.

have a nice day !

**Comment by lamontfr** [comment]
@erozqba 

Here are some comments : 
- The daily menus (which include the Menu_components=specific dishes for a date) must have been created *before* adding orders for a given date. I wrote the staticmethod (meal/models.py) Menu.create_menu_and_components(menu_date, dish_names) for that. In order/management/commands/generateorders.py I do not see the need for MenuFactory.create(date=delivery_date), unless there is something I do not understand.
- More to come later ...

**Comment by manumilou** [comment]
@erozqba I like the idea of using generic views as much as possible. I guess you should go on this direction.

**Comment by erozqba** [comment]
@lamontfr @manumilou thanks for taking the time to look at this.
@lamontfr I will check again, but I have an error when I was trying to generate new orders for a day without a menu.
I have a question for you @manumilou, with this form the user should be able to add new Components to the Order_items too? Something similar to the form Create Order_item from django-admin? Or this is not necessary?

I will add the tests for this, then.

**Comment by lamontfr** [comment]
@erozqba I had a discussion with @manumilou this afternoon and we decided that I will remove the requirement to have menus before creating orders. I am working on a new version of create_orders_on_defaults() and should post it tomorrow.

**Comment by manumilou** [comment]
What do you mean by adding new components to the order item? An order item should be created among the existing components.

Le 2 août 2016 17:28:08 HAE, Ernesto Rodriguez Ortiz <notifications@github.com> a écrit :
>@lamontfr @manumilou thanks for taking the time to look at this.
>@lamontfr I will check again, but I have an error when I was trying to
>generate new orders for a day without a menu.
>I have a question for you @manumilou, with this form the user should be
>able to add new Components to the Order_items too? Something similar to
>the form Create Order_item from django-admin? Or this is not necessary?
>
>I will add the tests for this, then.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/savoirfairelinux/santropol-feast/pull/288#issuecomment-237049881

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by erozqba** [comment]
I'm closing this PR, is easier to commit the rebased work of this branch over dev in a new branch and reopen the PR.

**Comment by manumilou** [comment]
Ok @erozqba .

**Pull request closed without merging**
