### PR TITLE
Add admin panel

### LINKED ISSUE #16: Integrate models in the admin panel of django

### PR DESCRIPTION
**Pull request by RignonNoel**
fixed #16 

Add all models in admin panels.
We can't try this until you have accept a PR for debug models and create first migrations

### CODE REVIEW

**Comment by manumilou** [comment]
@RignonNoel Which PR is blocking?

**Comment by manumilou** [comment]
@RignonNoel You probably should only rebase this PR on the latest master branch.

**Comment by RignonNoel** [comment]
A PR who has no create for now.

I will try to correct model tomorrow before the meeting. I expect you've validated my other PR of standard before.

**Comment by RignonNoel** [comment]
Yes i just need to rebase to pass tests, it's sûre!

But you can't test the functionnality without à good model. The runserver command don't work for the moment.

**Comment by manumilou** [comment]
OK we'll see tomorrow then!
https://github.com/savoirfairelinux/santropol-feast/pull/15 is merged already.

**Pull request merged**
