### PR TITLE
Visual Data Model as UML Class diagram

### PR DESCRIPTION
**Pull request by lamontfr**
In order to facilitate understanding the overall data model, I created one in PlantUML notation and generated the image. The data model includes all the classes and relations currently on the models.py from all the apps.

PlantUML format is a plain text file which allows to see changes made to it using standard code "diffing" tools. PlantUML http://plantuml.com/ has integrations for most IDEs and also has server based generators http://plantuml.com/server.html

Francois Lamontagne

### CODE REVIEW

**Comment by RignonNoel** [comment]
Thanks! I like that.

However i know a way to link directly the picture in function of the text in Github. We just need to put the text in Github, and the picture is generated on each Http request on the page.

It's more simple and we are sure to have the latest version of the picture.

I'll just look in my notes and I'll come back on this.

**Comment by RignonNoel** [comment]
I've found:
```
![diagram in UML](http://www.plantuml.com/plantuml/proxy?fmt=svg&src=YOUR_URL.UML)
```

So here it will be:
```
![diagram in UML](http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://raw.githubusercontent.com/savoirfairelinux/santropol-feast/dev/docs/data_model.uml)
```

We put this image in markdown in the documentation, wiki, or other and it will be always update with your uml file.

**Comment by manumilou** [comment]
@lamontfr Can you make an interactive rebase on your commits, to keep one or two clean commit messages ? Thanks in advance!

**Comment by lamontfr** [comment]
I am sorry about the "noise" I caused today. I did only one pull request last night. After that I was working on my fork and I thought that it was not propagated to the main repo. I will try and fix this.

**Comment by RignonNoel** [comment]
It's not a problem, you do not have to apologize! :+1: 

---

For fix you can simply ```git reset HEAD~n``` with n the number of commit you want undo.

This command keep the change, you have just to ```git add``` and ```git commit``` the new commit with all update you have make.

**Comment by lamontfr** [comment]
I didi not change/delete file "django/santropolFeast/meal/\". I do not know why it got in commit 744e297. Please bear with me, I will fix it ! 
What I want to submit here is only the docs/data_model/ folder and its contents.

**Comment by RignonNoel** [comment]
This is the same solution for this problem.

```
git reset HEAD~1 (undo the last commit)
git reser HEAD (untrack file)
git add FILE_YOU_WANT_ONLY (track file)
git commit -m "your_message" (create a new commit who contain file tracked)
git push -f origin your_branche (force push changement to your fork and update the PR)
```

**Comment by lamontfr** [comment]
File "santropol-feast/django/santropolFeast/meal/ \" the file name is "\" (single backslash) was added on March 21 and it contains python code ! This file name causes a path error on Windows, such that the git cache index gets confused and commands such as git reset produce errors. I had to use a Debian machine to correct the problem (my last two commits). Even on Linux a file named "\" is a pain because \ is an escape character. Until I buy a Macbook next month, I am stuck with a Windows laptop. I suggest changing that file name to something-else.py. Thanks !

**Comment by lamontfr** [comment]
By the way, my pull request is now complete. I added a data_model folder to docs/. This includes a data model in PlantUML text format (.uml) and a image (.png) (see my initial comment in this pull request). Then, as suggested by Noël, I added a readme.md file that has a URL to the .uml file such that the image is dynamically generated inline.

Francois L.

**Comment by RignonNoel** [comment]
Hi François,

It's ok for me, but you need to group all commit in one or two commit only.
Here you have 17 commits.

If you have difficulty with git, you can simply copy your work (3 new files), delete this branch and create a new one from ```dev``` where you paste your work and create a commit.

**Comment by lamontfr** [comment]
Hi Noel,
1- Before I create a new branch, can someone fix the file "santropol-feast/django/santropolFeast/meal/ \" (see my comment above).
2- Can I close or cancel this PR, then make a fresh new PR with a new commit of my 3 files ?

**Comment by lamontfr** [comment]
Noel : Maxime fixed the file named "\".

**Comment by manumilou** [comment]
The file has been deleted.

@lamontfr You can close this PR and create a new one. Please just reference one to the other in the description, by adding a link to this PR. This way we limit the risk to lose information.

**Pull request closed without merging**
