### PR TITLE
Rename "Diabetic Dessert" to "Diabetic" to work around #833.

### PR DESCRIPTION
**Pull request by kousu**
### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

*Fill out this section so that a reviewer can know how to verify your change.*

1. [Make a new order](http://127.0.0.1:8000/order/create/batch).
  - add 2 Diabetic Dessert
  - add 3 Green Salad
2. Go through the [Kitchen Count flow](http://127.0.0.1:8000/delivery/order/); confirm everything necessary
3. Print out the [route sheets](http://127.0.0.1:8000/delivery/routes/?print=yes)
  - you should see that your order is laid out like
    Diabetic   2
    Dessert   3
    Green Salad

Stop your docker instance, if applicable, pull the code, and put your docker instance back up if applicable. *Run the migration*: `cd src; python manage.py migrate`

Re-print the kitchen count. It should now be laid out like
    Diabetic   2
    Green Salad 3

### Deployment notes and migration

- [x] Migration is needed for this change

### New translatable strings

- [x] If applicable, I have included updated .po files with new strings (see https://github.com/savoirfairelinux/sous-chef/blob/dev/docs/internationalization.adoc)

### Additional notes

This is not the final patch for #833; as I explained on that ticket, there's a deeper problem here. But it fixes the problem for now, and that's all we need.

### CODE REVIEW

**Comment by erozqba** [comment]
@JeanFrancoisFournier are you OK with renaming "Diabetic Dessert" to "Diabetic" to work around #833?

**Comment by kkonieczny** [comment]
@erozqba is this MR still relevant?

**Comment by erozqba** [comment]
@kkonieczny no idea, I make a question to @JeanFrancoisFournier but no anwser.

**Comment by JeanFrancoisFournier** [comment]
Perfectly fine with the work around solution. I actually suggested it to Nick.

The "diabetic dessert" text was changed to just  "diabetic" by @kousu. This is all we needed to avoid confusing with the volunteers using the route sheets with this line break issue. 

The only issue remaining with this is that if in the future, the kitchen crew decided to add a new side dish option for clients, they would have to limit the length of the name for that side dish to avoid line break issues again. (i.e. no long names).

Hope that answers your question and Thanks!

**Comment by JeanFrancoisFournier** [comment]
Hi Ernesto,

Sorry, I made a comment on the GitHub. Maybe it was not the right place to
answer. Maybe not the right issue commented either... sorry

Just commented  right below you on issue #837

Thanks again for your support!

-- 
<https://www.santropolroulant.org/>

*Jean-François Fournier*

*Coordonnateur de la Communauté de Clients de la Popote-Roulante
Coordinator of the Meals-on-Wheels Client Community *
514 284-9335 <514-284-9335>

Nourish your community - become a monthly donor
<https://santropolroulant.org/en/2017/05/2017-monthly-giving-campaign-roulant-roots/>

<http://www.facebook.com/sroulant> <http://twitter.com/SRoulant>
<http://instagram.com/SRoulant>
<https://www.linkedin.com/company/santropol-roulant>
<https://www.youtube.com/channel/UCFYRQO2HSNs6wJMA1as5zhg>
<https://santropolroulant.org/publications/newsletters/>
<https://www.canadahelps.org/dn/12292>

**Comment by kousu** [comment]
Hey all, this PR has been languishing. It looks like it has the approval of @JeanFrancoisFournier. I'd appreciate if @erozqba or @JeanFrancoisFournier could click the Merge button.

**Comment by erozqba** [comment]
@kousu I would love to, but I don't have access to do that. I'm not longer at Savoir-faire Linux and my permissions to approve PR has been removed. @kkonieczny could you take care of this?

**Comment by JeanFrancoisFournier** [comment]
@kousu and @erozqba Is it as easy as clicking the "Merge pull request" button. I can so that now!

**Pull request merged**
