### PR TITLE
Create new member - add map for adress validation

### PR DESCRIPTION
**Pull request by rjacquemin**
*Fixes # .*

### Changes proposed in this pull request:

* New member - add a map for validation at address step 
* ...
* ...

### Status

- [X ] READY
- [ ] HOLD
- [] WIP (Work-In-Progress)

### Deployment notes and migration

- [ ] Migration needed

Fill me in ...

@savoirfairelinux/mll

### CODE REVIEW

**Comment by maximest-pierre** [comment]
Are you ready to merge, I saw that you added some commit after the PR was open.

**Comment by rjacquemin** [comment]
It is ready .

Just did rebase when I saw PR was not merge automatically


2016-08-08 15:43 GMT-04:00 Maxime St-Pierre <notifications@github.com>:

**Comment by maximest-pierre** [comment]
Perfect, I will test it and then merge it.

**Comment by maximest-pierre** [comment]
Thanks

**Pull request merged**
