### PR TITLE
Fix error in the Step Allergies to show the components Pudding and Co…

### LINKED ISSUE #256: Default Meals in the Client creation form dont show "Pudding" and "Compote" component.
### Expected Behaviour

When completing the multi-step form to add a client, in the step Allergies (Restrictions, allergies, ...) we should see in the field **Meals default** the components  **Pudding** and **Compote**.

### Actual Behaviour

The components **Pudding** and **Compote** are not present in the form.

### PR DESCRIPTION
**Pull request by erozqba**
*Fixes #256 .*

### Changes proposed in this pull request:

* Show all components in default meals
* Remove not used templates and move 
* Show Meals default for the selected days only in the schedule. 

### Status

- [X] READY

### CODE REVIEW

**Comment by erozqba** [comment]
@manumilou, I was working in the Factory and find out this issue that need to fix in order to keep working in the Factory stuff, I have try to improve the form a little more, I hope this will be OK.

**Comment by erozqba** [comment]
Hi @manumilou, I will increase the coverage for this PR and made a rebase after the PR #258 has been merged.

**Comment by manumilou** [comment]
@erozqba #258 has been merged. Thanks Ernesto, great job!

**Comment by erozqba** [comment]
Hi @manumilou,
This PR also fix the issue #264 reported by @lamontfr, sorry for taken too long in doing the rebase.
I think is ready now.
Thanks in advance for the code review!

**Comment by lamontfr** [comment]
@erozqba Ernesto, 
If you want to fix issue 264 in this PR
django/santropolFeast/member/views.py lines 25-26 should be (see PR 265) :  

           context["weekday"] = [left for left, right in DAYS_OF_WEEK]
           context["meals"] = [left for left, right in COMPONENT_GROUP_CHOICES]

**Comment by erozqba** [comment]
Hi @lamontfr,
Check the changes in the file **templates/forms/steps/meal_defaults.html** lines **3** and **19** https://github.com/savoirfairelinux/santropol-feast/compare/issue_256_missing_fields
I use the tuples to display the correct translation for the day and the component in the template.

**Comment by lamontfr** [comment]
Hi Ernesto,

You did the right thing. Sorry about my overlook.

-Francois.

**Comment by erozqba** [comment]
Hi @lamontfr,
Is always great to have somebody looking into the code and making suggestions and comments.
Thanks again for taking the time to made the code review!

**Pull request merged**
