### PR TITLE
FIX297 Fixed all Kitchen Count Steps for demo

### LINKED ISSUE #297: Display the component group with the component name in the order view
### Expected Behaviour

- [X] The component group should be displayed in the order detail view
- [x] The component group (but not the component name) should be displayed in the update order view

### Actual Behaviour

* Empty if no component attached to the order item.
* Order update shows both component group and component name

### PR DESCRIPTION
**Pull request by lamontfr**
*Fixes #297 (I will refactor code later, this is a rush for the Demo today)*

### Changes proposed in this pull request:

* View order info : component group
* Choose main dish and Ingredients
* Kitchen count report

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### Deployment notes and migration

- [ ] Migration needed

@savoirfairelinux/mll

### CODE REVIEW

**Comment by manumilou** [comment]
@lamontfr It breaks at the step 3, see attached screenshot. Should I completly flush my database before running your script ?

capture d ecran de 2016-08-04 10-55-39

**Comment by lamontfr** [comment]
@manumilou Here are the commands that work for me : 

python dataexec.py
python manage.py generateorders 2016-08-04
python manage.py runserver
Browse to SousChef
Click "Kitchen Count"  (= /delivery/order/) : See order list for august 4
Click "View order" : see details
Back  (= /delivery/order/)
Click  / "OK I'm Ready" to get to page /delivery/meal/
In Pull down Choose "Ginger Pork", click "Change"
see main dish recipe, hover / click on widget to change ingredients
Click "Next - Print Kitchen Count", see ingredients today and clients clashes
Click "Back", can change ingredients and so on.

**Comment by maximest-pierre** [comment]
I got the same problem as @manumilou with a clean DB

**Comment by lamontfr** [comment]
Can you give me the file name and the line number where the error occurs ?

**Comment by maximest-pierre** [comment]
Traceback:

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/code/django/santropolFeast/delivery/views.py" in post
  151.                      'Day s Pudding', 'Day s Compote'])

File "/code/django/santropolFeast/meal/models.py" in create_menu_and_components
  217.             menu = Menu.objects.get(date=menu_date)

File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py" in manager_method
  122.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py" in get
  391.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /delivery/meal/
Exception Value: get() returned more than one Menu -- it returned 2!

**Comment by lamontfr** [comment]
@maximest-pierre @manumilou I think I know why. Give me a minute.

**Comment by lamontfr** [comment]
@manumilou @maximest-pierre Please try again, starting with python dataexec.py.

**Comment by maximest-pierre** [comment]
I just tried it. Its the same thing.

**Comment by lamontfr** [comment]
@manumilou There were some menus left in the previous file.

This dataload.py file has no more menus in it, May be good to flush the DB.

**Comment by maximest-pierre** [comment]
With the new dataload everything seems to work fine.

**Comment by lamontfr** [comment]
@manumilou I am currently fixing this PR, please wait for my next commit.

**Comment by lamontfr** [comment]
I am closing this PR and will make a new one.

**Pull request closed without merging**
