### PR TITLE
Basic documentation setup with Sphinx

### LINKED ISSUE #50: Generate developer documentation from docstring with Sphinx
The user documentation (manual) should be written with [Sphinx](http://www.sphinx-doc.org/en/stable/) and hosted on ReadTheDocs.org.

### PR DESCRIPTION
**Pull request by discardthree**
I'm making a PR so people can see where this is at, but let's keep it at WIP status until I fix some problems and sphinx is generating something non-empty.

----
RignonNoel add:
fixed #50

### CODE REVIEW

**Comment by discardthree** [comment]
This will be ready to merge when:
- [ ] 'make html' isn't throwing any errors
- [ ] the generated index.html has a meaningful table of contents
- [ ] at least one module has been fully documented with docstrings, so we can use it as a sample
- [ ] we're happy (at least for now) with how the documentation for that fully documented module is rendered.
- [ ] an issue has been created to explain how docstrings should be written, and to ask people to begin writing them

**Comment by discardthree** [comment]
I was planning to continue working on this at your next hack night, but I have a prior engagement to run a hack night for PyLadies this Thursday.  If anyone at the hack night wants to pick this PR up and work on it, feel free.

**Comment by discardthree** [comment]
This is ready to merge.

**Comment by manumilou** [comment]
@discardthree Can you rebase it so it could be merged?

**Comment by discardthree** [comment]
Moving target, I just fixed the PEP8 errors but I see you fixed them also... rebasing once more.

**Comment by discardthree** [comment]
Okay, we're good again.

**Pull request merged**
